name: combine

on:
  pull_request:
  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('./yarn.lock') }}

      - name: yarn-install
        run: |
            yarn install
            CHANGES=$(git status -s)
            if [[ ! -z $CHANGES ]]; then
              echo "Changes found: $CHANGES"
              git diff
              exit 1
            fi

      - name: configure-git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: combine-data
        run: |
          echo "Assembling chain metadata and addresses together..."
          yarn build

      - name: commit-changes
        run: |
          CHANGES=$(git status -s)
          if [[ ! -z $CHANGES ]]; then
            git add .
            git commit -m "Update chain metadata and address files"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.COMBINE_CI_TOKEN }}